version: '3.8'

services:
  modsen_psql:
    image: postgres:latest
    container_name: modsen_psql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: modsen_db
    ports:
      - "5432:5432"
    volumes:
      - modsen_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  modsen_pg_data: